# Generated by Django 2.2.15 on 2020-11-20 23:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OauthWeiXin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(db_index=True, max_length=64, verbose_name='openid')),
                ('ser', models.ForeignKey(on_delete=True, related_name='wx', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '微信第三方登录',
                'verbose_name_plural': '微信第三方登录',
                'db_table': 'wx_oauth',
            },
        ),
        migrations.CreateModel(
            name='OauthQQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(db_index=True, max_length=64, verbose_name='openid')),
                ('user', models.ForeignKey(on_delete=True, related_name='qq', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'QQ第三方登录',
                'verbose_name_plural': 'QQ第三方登录',
                'db_table': 'qq_oauth',
            },
        ),
    ]
