# Generated by Django 2.2.15 on 2020-10-20 19:27

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.SmallIntegerField(choices=[(1, '一星好评'), (2, '二星好评'), (3, '三星好评'), (4, '四星好评'), (5, '五星好评')], help_text='Please rate the goods', verbose_name='评分')),
                ('reward_content', models.TextField(help_text='Please enter a comment', max_length=128, verbose_name='评论内容')),
                ('reward_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('is_remark', models.BooleanField(default=True)),
                ('praise', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('against', models.PositiveIntegerField(default=0, verbose_name='差评数')),
                ('is_action', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '评论表',
                'verbose_name_plural': '评论表',
                'db_table': 'Remark',
            },
            managers=[
                ('remark_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Remark_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_content', models.TextField(help_text='Please enter a comment', verbose_name='评论内容')),
                ('reply_time', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('praise', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('against', models.PositiveIntegerField(default=0, verbose_name='差评数')),
                ('is_action', models.BooleanField(default=False)),
                ('remark', models.ForeignKey(help_text='请填写对评论的回复', on_delete=django.db.models.deletion.CASCADE, related_name='remark_reply', to='remark_app.Remark', verbose_name='评论')),
            ],
            options={
                'verbose_name': '评论回复表',
                'verbose_name_plural': '评论回复表',
                'db_table': 'Remark_reply',
            },
        ),
    ]
