# Generated by Django 2.2.15 on 2020-10-20 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('remark_app', '0001_initial'),
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark_reply',
            name='shopper',
            field=models.OneToOneField(help_text='商家', on_delete=django.db.models.deletion.CASCADE, related_name='remark_reply', to=settings.AUTH_USER_MODEL, verbose_name='商家'),
        ),
        migrations.AddField(
            model_name='remark',
            name='commodity',
            field=models.ForeignKey(help_text='您所评分的商品', on_delete=django.db.models.deletion.CASCADE, related_name='remark', to='shop_app.Commodity', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='remark',
            name='consumer',
            field=models.ForeignKey(help_text='您所评分的商家', on_delete=django.db.models.deletion.CASCADE, related_name='remark_consumer', to=settings.AUTH_USER_MODEL, verbose_name='消费者'),
        ),
        migrations.AddField(
            model_name='remark',
            name='shopper',
            field=models.ForeignKey(help_text='评论的商家', on_delete=django.db.models.deletion.CASCADE, related_name='remark_shopper', to=settings.AUTH_USER_MODEL, verbose_name='商家'),
        ),
    ]
