# Generated by Django 2.2.15 on 2020-10-20 19:27

import django.core.validators
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_status', models.SmallIntegerField(choices=[(1, '未发货'), (2, '已发货')], default=1, verbose_name='发货状态')),
                ('signed', models.BooleanField(default=False, verbose_name='是否签收')),
            ],
            options={
                'verbose_name': '物流表',
                'verbose_name_plural': '物流表',
                'db_table': 'Logistic',
            },
        ),
        migrations.CreateModel(
            name='Order_basic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=100, verbose_name='支付流水号')),
                ('payment', models.CharField(choices=[('1', '货到付款'), ('2', '微信支付'), ('3', '支付宝'), ('4', '银联支付')], max_length=1, verbose_name='支付方式')),
                ('commodity_total_counts', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10000, message='订单中商品总数不超过10000件')], verbose_name='商品总数')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MaxValueValidator(99999999.99, message='商品的总价格不能超过999999.99人民币')], verbose_name='商品总价格')),
                ('generate_time', models.DateTimeField(auto_now_add=True, verbose_name='生成订单时间')),
                ('check_time', models.DateTimeField(auto_now=True, verbose_name='审核完毕订单时间')),
                ('trade_number', models.CharField(max_length=128, null=True, verbose_name='交易编号')),
                ('status', models.CharField(choices=[('1', '代付款'), ('2', '代发货'), ('3', '代收货'), ('4', '交易成功'), ('5', '已取消'), ('6', '售后中'), ('7', '交易关闭'), ('8', '正在退货'), ('9', '退款成功')], default=1, max_length=1, verbose_name='订单状态')),
                ('checked', models.BooleanField(default=False, verbose_name='是否审核')),
                ('remarked', models.BooleanField(default=False, verbose_name='是否可以评论')),
                ('delete_consumer', models.BooleanField(default=False, verbose_name='消费者是否删除订单')),
                ('delete_shopper', models.BooleanField(default=False, verbose_name='商家是否删除订单')),
                ('efficient_time', models.DateTimeField(auto_now=True, null=True, verbose_name='订单过期时间')),
            ],
            options={
                'verbose_name': '订单信息表',
                'verbose_name_plural': '订单信息表',
                'db_table': 'Order_basic',
            },
            managers=[
                ('order_basic_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MaxValueValidator(999999.99, message='商品的最高单价不能超过999999.99人民币'), django.core.validators.MinValueValidator(0, message='商品价格必须为正数')], verbose_name='商品价格')),
                ('commodity_counts', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10000, message='订单中商品总数不超过10000件')], verbose_name='商品总数')),
                ('label', models.CharField(default='无', max_length=25)),
            ],
            options={
                'verbose_name': '订单商品详情表',
                'verbose_name_plural': '订单商品详情表',
                'db_table': 'Order_details',
            },
            managers=[
                ('order_details_', django.db.models.manager.Manager()),
            ],
        ),
    ]
