# Generated by Django 2.2 on 2020-07-24 18:01

import User_app.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_image', models.ImageField(blank=True, help_text='上传您的头像', null=True, upload_to='head', verbose_name='头像')),
                ('birthday', models.DateTimeField(blank=True, help_text='填写您的出生日期', null=True, verbose_name='生日')),
                ('sex', models.CharField(choices=[('m', '男'), ('f', '女'), ('s', '保密')], default='s', help_text='填写您的性别', max_length=1, verbose_name='性别')),
                ('phone', models.CharField(blank=True, help_text='填写您的手机号', max_length=11, null=True, verbose_name='手机号')),
                ('rank', models.CharField(choices=[(1, '先锋会员'), (2, '卫士会员'), (3, '中军会员'), (4, '统帅会员'), (5, '传奇会员'), (6, '万古流芳会员'), (7, '超凡入圣会员'), (8, '冠绝一世会员')], default=1, help_text='您的会员等级', max_length=1, verbose_name='会员等级')),
                ('safety', models.DecimalField(decimal_places=0, default=60, help_text='您的信息安全分数', max_digits=3, verbose_name='安全分数')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consumer', to=settings.AUTH_USER_MODEL, verbose_name='消费者')),
            ],
            options={
                'verbose_name': '消费者',
                'verbose_name_plural': '消费者',
                'db_table': 'Consumer',
            },
            managers=[
                ('consumer_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.CharField(max_length=20, validators=[User_app.validators.RecipientsValidator()], verbose_name='收件人')),
                ('region', models.CharField(max_length=100, verbose_name='所在地区')),
                ('address_tags', models.CharField(choices=[('1', '家'), ('2', '公司'), ('3', '学校')], max_length=1, verbose_name='地址标签')),
                ('default_address', models.BooleanField(default=False, verbose_name='默认地址')),
                ('phone', models.CharField(error_messages={'unique': 'A telephone number with this already exists.'}, help_text='Please write your cell-phone number', max_length=11, validators=[User_app.validators.PhoneValidator()], verbose_name='手机号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL, verbose_name='消费者')),
            ],
            options={
                'verbose_name': '收获地址',
                'verbose_name_plural': '收获地址',
                'db_table': 'Address',
                'ordering': ('-default_address',),
            },
            managers=[
                ('address_', django.db.models.manager.Manager()),
            ],
        ),
    ]
