# Generated by Django 2.2.15 on 2020-10-20 19:27

import django.core.validators
from django.db import migrations, models
import django.db.models.manager
import mdeditor.fields
import shop_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(help_text='Please enter the name of the product', max_length=50, validators=[shop_app.validators.CommodityValidator()], verbose_name='商品名称')),
                ('price', models.PositiveIntegerField(help_text='Please enter the price of the goods', validators=[django.core.validators.MaxValueValidator(999999, message='商品最高价格不能高于999999')], verbose_name='价格')),
                ('details', mdeditor.fields.MDTextField(help_text='Please describe your product in detail', verbose_name='商品的详细描述')),
                ('intro', models.TextField(help_text='A briefly describe', max_length=100, verbose_name='商品的简要描述')),
                ('category', models.CharField(choices=[('衣服', '衣服'), ('裤子', '裤子'), ('鞋子', '鞋子'), ('电子设备', '电子设备'), ('化妆品', '化妆品'), ('食品', '食品'), ('帽子', '帽子'), ('袜子', '袜子'), ('游戏', '游戏'), ('户外装备', '户外装备'), ('手表', '手表'), ('饰品', '饰品'), ('生活用品', '生活用品'), ('家居', '家居'), ('其他', '其他')], help_text='Please select the type of goods', max_length=10, verbose_name='商品类别')),
                ('status', models.BooleanField(default=False, help_text='请选择商品是否上架', verbose_name='上架状态')),
                ('onshelve_time', models.DateTimeField(auto_now=True, verbose_name='上架时间')),
                ('unshelve_time', models.DateTimeField(auto_now=True, verbose_name='下架时间')),
                ('discounts', models.DecimalField(decimal_places=1, default=1.0, help_text='是否在节假日打折,打几折？', max_digits=2, verbose_name='是否优惠')),
                ('sell_counts', models.PositiveIntegerField(default=0, verbose_name='销售量')),
                ('freight', models.PositiveIntegerField(default=0, help_text='该商品是否有运费', verbose_name='运费')),
                ('image', models.ImageField(help_text='商品主图片', null=True, upload_to='commodity_head', verbose_name='图片')),
                ('label', models.TextField(verbose_name='商品标签')),
                ('discounts_intro', models.TextField(default='该店铺目前暂无优惠活动', help_text='请对优惠活动进行说明', max_length=100, verbose_name='优惠活动说明')),
                ('stock', models.IntegerField(default=5000, help_text='请修改您的库存量', verbose_name='库存')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
                'db_table': 'Commodity',
            },
            managers=[
                ('commodity_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Goodsby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(help_text='Please enter the name of the product', max_length=100, verbose_name='商品名称')),
                ('picture', models.ImageField(upload_to='carousel', verbose_name='轮播图片')),
                ('url', models.URLField(max_length=20, verbose_name='商品链接')),
            ],
            options={
                'verbose_name': '首页轮播商品',
                'verbose_name_plural': '首页轮播商品',
                'db_table': 'Carousel_index',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, verbose_name='种类名称')),
                ('logo', models.CharField(max_length=20, verbose_name='logo标识')),
                ('image', models.ImageField(upload_to='category', verbose_name='图片')),
            ],
            options={
                'verbose_name': '商品类型',
                'verbose_name_plural': '商品类型',
                'db_table': 'Commodity_category',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('url', models.URLField(max_length=20, verbose_name='活动链接')),
                ('picture', models.ImageField(upload_to='promotion', verbose_name='促销商品图片')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='活动持续时间')),
                ('end_time', models.DateTimeField(auto_now_add=True, verbose_name='活动结束时间')),
            ],
            options={
                'verbose_name': '促销商品',
                'verbose_name_plural': '促销商品',
                'db_table': 'Promotion_commodity',
            },
        ),
    ]
