# Generated by Django 2.2.15 on 2020-10-20 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0001_initial'),
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='shopper',
            field=models.ForeignKey(help_text='商品所属的商家', on_delete=django.db.models.deletion.CASCADE, related_name='commodity', to=settings.AUTH_USER_MODEL, verbose_name='商家'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='store',
            field=models.ForeignKey(help_text='商品所在的店铺', on_delete=django.db.models.deletion.CASCADE, related_name='commodity', to='user_app.Store', verbose_name='商铺'),
        ),
    ]
