# Generated by Django 2.2.15 on 2020-10-20 19:27

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(max_length=100, verbose_name='支付流水号')),
                ('generate_time', models.DateTimeField(auto_now_add=True, verbose_name='完成交易')),
                ('order_basic', models.OneToOneField(on_delete=True, related_name='PayInformation', to='order_app.Order_basic', verbose_name='订单基本表')),
            ],
            options={
                'verbose_name': '支付信息',
                'verbose_name_plural': '支付信息',
                'db_table': 'PayInformation',
            },
            managers=[
                ('payment_', django.db.models.manager.Manager()),
            ],
        ),
    ]
