# Generated by Django 2.2 on 2020-07-24 18:01

import Shopper_app.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(help_text='请定义您的商铺名，默认为您的有户名+"的商铺"', max_length=30, verbose_name='店铺')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('province', models.CharField(blank=True, help_text='请填写您的省份', max_length=10, verbose_name='省份')),
                ('attention', models.PositiveIntegerField(default=0, verbose_name='关注量')),
                ('shop_grade', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='店铺评分')),
                ('shopper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL, verbose_name='商家')),
            ],
            options={
                'verbose_name': '店铺',
                'verbose_name_plural': '店铺',
            },
            managers=[
                ('store_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Shoppers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, validators=[Shopper_app.validators.PhoneValidator()], verbose_name='手机号')),
                ('credit', models.CharField(choices=[('1', '1星'), ('2', '2星'), ('3', '3星'), ('4', '4星'), ('5', '5星'), ('6', '1钻'), ('7', '2钻'), ('8', '3钻'), ('9', '4钻'), ('10', '5钻')], default=1, help_text='您的信誉等级', max_length=1, verbose_name='信誉')),
                ('sex', models.CharField(blank=True, choices=[('m', '男'), ('f', '女')], help_text='性别', max_length=1, validators=[Shopper_app.validators.validate_sex], verbose_name='性别')),
                ('head_image', models.ImageField(blank=True, help_text='Please upload your portrait', null=True, upload_to='head', verbose_name='头像')),
                ('is_vip', models.BooleanField(default=True, verbose_name='是否是vip')),
                ('birthday', models.DateTimeField(blank=True, help_text='填写您的出生日期', null=True, verbose_name='生日')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shoppers', to=settings.AUTH_USER_MODEL, verbose_name='商家id')),
            ],
            options={
                'verbose_name': '商家',
                'verbose_name_plural': '商家',
            },
            managers=[
                ('shopper_', django.db.models.manager.Manager()),
            ],
        ),
    ]
