# Generated by Django 2.2.15 on 2021-02-15 11:32

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='权限名')),
                ('pid', models.CharField(max_length=8, unique=True, verbose_name='权限代码')),
                ('description', models.CharField(max_length=128, verbose_name='权限描述')),
            ],
            options={
                'db_table': 'manager_permission',
            },
            managers=[
                ('manager_permission_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ManagerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=15, verbose_name='角色名')),
                ('description', models.CharField(max_length=128, verbose_name='角色描述')),
                ('rid', models.CharField(max_length=8, unique=True, verbose_name='角色代码')),
            ],
            options={
                'db_table': 'manager_role',
            },
            managers=[
                ('role_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=False, related_name='manager', to='manager_app.ManagerRole')),
            ],
            options={
                'db_table': 'managers',
            },
            managers=[
                ('manager_', django.db.models.manager.Manager()),
            ],
        ),
    ]
