# Generated by Django 2.2.15 on 2021-02-15 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='管理者'),
        ),
        migrations.AddField(
            model_name='managerrole',
            name='permission',
            field=models.ManyToManyField(related_name='role', to='manager_app.ManagerPermission'),
        ),
    ]
