# Generated by Django 2.2.15 on 2021-02-15 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0002_auto_20210215_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='manager_app.ManagerRole'),
        ),
    ]
